spring:
  application:
    name: testApp

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/demo
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations=classpath:mappers/*.xml